services:
  frontend:
    build: frontend/
    depends_on:
      - backend
    ports:
      - "3000:3000"
    container_name: frontend
  backend:
    build: backend/
    ports:
      - "8080:8080"
    container_name: backend